apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: boldbi-designer-ingress
  namespace: boldbi-cloud-test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4 256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "4 16k"
    nginx.ingress.kubernetes.io/fastcgi-buffers: "16 16k"
    nginx.ingress.kubernetes.io/fastcgi-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/affinity: cookie
    # nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    # nginx.ingress.kubernetes.io/session-cookie-name: "bold.k8s.pod.id"
    # nginx.ingress.kubernetes.io/session-cookie-max-age: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_max_body_size 200m;
spec:
  tls:
  - hosts:
    - data-ds-1.boldbi.com
    - data-ds-2.boldbi.com
    secretName: boldbi-tls
  rules:
  - host: data-ds-1.boldbi.com
    http:
      paths:
      - backend:
          serviceName: bi-dataservice-service
          servicePort: 6007
        path: /
        pathType: ImplementationSpecific
  - host: data-ds-2.boldbi.com
    http:
      paths:
      - backend:
          serviceName: bi-refresh-service-service
          servicePort: 6008
        path: /
        pathType: ImplementationSpecific
