apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-refresh-service-deployment
  namespace: boldbi-cloud-test
spec:
  selector:
    matchLabels:
      app: bi-refresh-service
  # replicas: 1
  template:
    metadata:
      labels:
        app: bi-refresh-service
    spec:
      containers:
      - name: bi-refresh-service-container
        image: us-docker.pkg.dev/boldbi-dev-296107/boldbik8s/boldbi-designer-cloud:5.5.555202206021835583017
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750M
          limits:
            cpu: 250m
            memory: 750M
        envFrom:
        - secretRef:
              name: boldbi-designer-secret
        readinessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
