apiVersion: v1
kind: Service
metadata:
  name: bi-dataservice-refresh-service
  namespace: boldbi-cloud-test  
  annotations:
    cloud.google.com/backend-config: '{"default": "development-backend"}'
  labels:
    app: bi-refresh-service
spec:
  type: NodePort
  ports:
  - name: bi-refresh-service-port
    port: 6008
    targetPort: 80
    protocol: TCP
  selector:
    app: bi-refresh-service
